In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [5]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# Text Cleaning
- 1.Sample 10000 rows
- 2.Remove html tags
- 3.Remove special characters
- 4.Convert to lower case
- 5.Removing stop words
- 6.Stemming

In [6]:
df  = df.sample(10000)

In [7]:
df.shape

(10000, 2)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 13088 to 6197
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [7]:
df['sentiment'] = df['sentiment'].replace({'positive':1 , 'negative':0})

In [20]:

df.reset_index(inplace=True , drop=True)
df.head()

                                              review  sentiment
0  If you can watch a Bond film from 1983 that is...          1
1  I saw this movie again as an assignment for my...          1
2  It's dreadful rubbish. I liked 'How Do You Wan...          0
3  Having spent all of her money caring for her t...          0
4  In & Out is a comedy with a simple premise. It...          1

In [21]:
import re

In [22]:
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean , '', text)

In [23]:
df['review'] = df['review'].apply(clean_html)

In [12]:
import nltk

In [13]:
from nltk.corpus import stopwords

In [15]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [14]:
len(stopwords.words('english'))

179

In [24]:
df['review'][0]

"If you can watch a Bond film from 1983 that isn't as good as Octopussy and still enjoy it.If you can accept production values which aren't that much above the level of a TV movie.If you can look at Sean Connery with wrinkles on his forehead beneath an obvious toupée and still see James Bond.If you can get past an inexperienced Basinger, a weaker Largo and a jolly Q.If you can learn to love an idiosyncratic score, not up there with Barry on his worst day.If you don't believe the hyperbolic reviews that it was greeted with on release.If you can meet a poker battle and a video game face off and enjoy them both the same.Yours is Never Say Never Again and everything that's in it.And, what is more, you'll probably enjoy it, my son!"

In [26]:
corpus = []

for i in range(len(df['review'])):
    
    text = re.sub('[^a-zA-Z]' , ' ' , df['review'][i])
    text = text.lower()
    text = text.split()
    
    text = [ps.stem(word) for word in text if word not in set(stopwords.words('english'))]
    
    text = ' '.join(text)
    corpus.append(text)

In [31]:
corpus[3]

'spent money care termin ill spous recent widow karen tunni lori heur move two daughter sarah scout taylor compton emma chloe moretz late husband run famili home rural pennsylvania local legend speak zombi roam wood night see name film writer director open credit enough send shiver spine boaz davidson geniu respons pen script stv titl octopu spider crocodil whilst j cardon gave us godaw video nasti slayer dull vampir flick forsaken dubiou talent respons expect much wick littl thing finish film glad kept expect low although movi look good time love use eeri woodland local cast give reason perform given clich drivel work plot labour poorli written deriv imposs enthusiast importantli perhap film killer undead children rise night mine die least bit scari smudg makeup black contact crappi joke shop scar littl add sens menac scout taylor compton compani best look afraid tini terror scream convincingli everi confront admir attempt instil sens fear audienc littl avail littl blighter got take chill blood lacklustr zombi chow scene futil bid win gore hound final kill see victim blood drench compton heur suitabl tasteless whole wick littl thing aka zombi uk instantli forgett trash anoth clunker filmographi cardon davidson'

In [29]:
df['review'] = corpus

In [30]:
df.head()

                                              review  sentiment
0  watch bond film good octopussi still enjoy acc...          1
1  saw movi assign manag class mainli comment dif...          1
2  dread rubbish like want father ted green wing ...          0
3  spent money care termin ill spous recent widow...          0
4  comedi simpl premis admir succe mission funni ...          1

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [33]:
X= cv.fit_transform(df['review']).toarray()

In [34]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
X.shape

(10000, 34902)

In [36]:
cv.vocabulary_

{'watch': 33593,
 'bond': 3456,
 'film': 10709,
 'good': 12454,
 'octopussi': 21571,
 'still': 29195,
 'enjoy': 9624,
 'accept': 148,
 'product': 24022,
 'valu': 32821,
 'much': 20415,
 'level': 17557,
 'tv': 31772,
 'movi': 20364,
 'look': 17970,
 'sean': 26929,
 'conneri': 6254,
 'wrinkl': 34358,
 'forehead': 11145,
 'beneath': 2713,
 'obviou': 21536,
 'toup': 31258,
 'see': 26986,
 'jame': 15609,
 'get': 12038,
 'past': 22557,
 'inexperienc': 15030,
 'basing': 2375,
 'weaker': 33651,
 'largo': 17167,
 'jolli': 15943,
 'learn': 17349,
 'love': 18072,
 'idiosyncrat': 14653,
 'score': 26802,
 'barri': 2325,
 'worst': 34306,
 'day': 7386,
 'believ': 2656,
 'hyperbol': 14555,
 'review': 25477,
 'greet': 12720,
 'releas': 25186,
 'meet': 19305,
 'poker': 23493,
 'battl': 2429,
 'video': 33108,
 'game': 11730,
 'face': 10250,
 'never': 20972,
 'say': 26565,
 'everyth': 9991,
 'probabl': 23992,
 'son': 28449,
 'saw': 26552,
 'assign': 1646,
 'manag': 18618,
 'class': 5643,
 'mainli': 18485,
 'comment': 6035,
 'differ': 8060,
 'style': 29502,
 'idea': 14632,
 'qualiti': 24434,
 'rent': 25275,
 'one': 21759,
 'back': 2025,
 'eighti': 9300,
 'rememb': 25224,
 'great': 12685,
 'alway': 812,
 'like': 17672,
 'michael': 19587,
 'keaton': 16346,
 'deliveri': 7643,
 'perfect': 22852,
 'fit': 10834,
 'surpris': 29826,
 'low': 18095,
 'rate': 24784,
 'grant': 12641,
 'ye': 34529,
 'oscar': 21948,
 'winner': 34076,
 'decent': 7494,
 'comed': 6012,
 'subtl': 29570,
 'comedi': 6013,
 'rather': 24789,
 'farc': 10379,
 'also': 777,
 'find': 10747,
 'felt': 10566,
 'inaccur': 14856,
 'cultur': 7020,
 'busi': 4279,
 'beg': 2598,
 'lot': 18027,
 'gener': 11940,
 'dramat': 8736,
 'hollywood': 14113,
 'documentari': 8462,
 'read': 24867,
 'automak': 1850,
 'side': 27683,
 'pacif': 22257,
 'time': 30937,
 'mani': 18666,
 'principl': 23960,
 'accur': 173,
 'basic': 2368,
 'japanes': 15649,
 'worker': 34273,
 'made': 18378,
 'feel': 10526,
 'part': 22509,
 'compani': 6068,
 'whole': 33905,
 'teamwork': 30379,
 'emphas': 9526,
 'perhap': 22865,
 'els': 9439,
 'american': 883,
 'vers': 33027,
 'labor': 16981,
 'type': 31837,
 'relationship': 25181,
 'individu': 14991,
 'import': 14819,
 'hate': 13418,
 'email': 9459,
 'sure': 29800,
 'anoth': 1138,
 'view': 33135,
 'whose': 33924,
 'respons': 25392,
 'fix': 10841,
 'plant': 23316,
 'defect': 7552,
 'problem': 23997,
 'examin': 10037,
 'discov': 8231,
 'charact': 5114,
 'put': 24364,
 'dealer': 7431,
 'mean': 19237,
 'car': 4624,
 'thing': 30734,
 'date': 7355,
 'around': 1504,
 'us': 32704,
 'maker': 18518,
 'struggl': 29434,
 'keep': 16365,
 'interest': 15244,
 'subject': 29530,
 'european': 9938,
 'recommend': 24983,
 'book': 3499,
 'studi': 29455,
 'detail': 7877,
 'done': 8559,
 'period': 22871,
 'call': 4445,
 'machin': 18327,
 'chang': 5081,
 'world': 34285,
 'womack': 34201,
 'daniel': 7268,
 'jone': 15952,
 'roo': 25874,
 'cover': 6655,
 'bit': 3057,
 'dri': 8798,
 'think': 30738,
 'dread': 8754,
 'rubbish': 26034,
 'want': 33521,
 'father': 10440,
 'ted': 30403,
 'green': 12701,
 'wing': 34063,
 'bill': 2976,
 'bailey': 2106,
 'standup': 28979,
 'act': 223,
 'file': 10699,
 'hippi': 13953,
 'planet': 23308,
 'ape': 1251,
 'imagin': 14727,
 'pedigre': 22723,
 'went': 33747,
 'badli': 2079,
 'wrong': 34370,
 'guess': 12896,
 'appeal': 1290,
 'peopl': 22814,
 'withnail': 34140,
 'overwritten': 22207,
 'littl': 17806,
 'end': 9572,
 'luvvi': 18250,
 'ish': 15457,
 'air': 522,
 'pervad': 22935,
 'bernard': 2792,
 'black': 3096,
 'simpli': 27789,
 'less': 17527,
 'camp': 4496,
 'thought': 30790,
 'self': 27036,
 'indulg': 15005,
 'even': 9964,
 'dylan': 9060,
 'moran': 20210,
 'becam': 2526,
 'writer': 34366,
 'set': 27180,
 'raidiat': 24623,
 'comic': 6023,
 'potenti': 23703,
 'first': 10811,
 'episiod': 9739,
 'notic': 21330,
 'slightest': 28048,
 'chortl': 5449,
 'worthi': 34309,
 'funni': 11578,
 'somehow': 28427,
 'regist': 25120,
 'mildli': 19686,
 'amus': 944,
 'someon': 28431,
 'write': 34364,
 'might': 19646,
 'would': 34316,
 'tri': 31485,
 'situat': 27875,
 'remark': 25216,
 'humor': 14453,
 'yet': 34572,
 'mundan': 20496,
 'gentl': 11969,
 'conscious': 6277,
 'surreal': 29828,
 'worth': 34308,
 'creat': 6771,
 'depict': 7773,
 'sitcom': 27866,
 'life': 17638,
 'short': 27550,
 'avoid': 1898,
 'spent': 28695,
 'money': 20095,
 'care': 4651,
 'termin': 30529,
 'ill': 14700,
 'spous': 28826,
 'recent': 24951,
 'widow': 33949,
 'karen': 16245,
 'tunni': 31708,
 'lori': 18011,
 'heur': 13820,
 'move': 20360,
 'two': 31818,
 'daughter': 7360,
 'sarah': 26446,
 'scout': 26822,
 'taylor': 30354,
 'compton': 6120,
 'emma': 9511,
 'chloe': 5408,
 'moretz': 20233,
 'late': 17211,
 'husband': 14502,
 'run': 26106,
 'famili': 10329,
 'home': 14137,
 'rural': 26124,
 'pennsylvania': 22799,
 'local': 17869,
 'legend': 17413,
 'speak': 28643,
 'zombi': 34844,
 'roam': 25731,
 'wood': 34220,
 'night': 21081,
 'name': 20672,
 'director': 8169,
 'open': 21818,
 'credit': 6780,
 'enough': 9638,
 'send': 27075,
 'shiver': 27505,
 'spine': 28734,
 'boaz': 3332,
 'davidson': 7373,
 'geniu': 11958,
 'pen': 22769,
 'script': 26869,
 'stv': 29500,
 'titl': 31018,
 'octopu': 21570,
 'spider': 28715,
 'crocodil': 6871,
 'whilst': 33845,
 'cardon': 4648,
 'gave': 11863,
 'godaw': 12364,
 'nasti': 20745,
 'slayer': 28002,
 'dull': 8928,
 'vampir': 32828,
 'flick': 10939,
 'forsaken': 11198,
 'dubiou': 8877,
 'talent': 30177,
 'expect': 10121,
 'wick': 33937,
 'finish': 10764,
 'glad': 12227,
 'kept': 16423,
 'although': 791,
 'use': 32713,
 'eeri': 9242,
 'woodland': 34229,
 'cast': 4811,
 'give': 12215,
 'reason': 24903,
 'perform': 22859,
 'given': 12217,
 'clich': 5721,
 'drivel': 8815,
 'work': 34268,
 'plot': 23396,
 'labour': 16986,
 'poorli': 23592,
 'written': 34369,
 'deriv': 7808,
 'imposs': 14823,
 'enthusiast': 9675,
 'importantli': 14820,
 'killer': 16532,
 'undead': 32106,
 'children': 5350,
 'rise': 25666,
 'mine': 19763,
 'die': 8046,
 'least': 17354,
 'scari': 26615,
 'smudg': 28197,
 'makeup': 18520,
 'contact': 6328,
 'crappi': 6730,
 'joke': 15931,
 'shop': 27541,
 'scar': 26605,
 'add': 255,
 'sens': 27086,
 'menac': 19395,
 'best': 2831,
 'afraid': 408,
 'tini': 30973,
 'terror': 30552,
 'scream': 26842,
 'convincingli': 6393,
 'everi': 9978,
 'confront': 6217,
 'admir': 305,
 'attempt': 1746,
 'instil': 15192,
 'fear': 10492,
 'audienc': 1777,
 'avail': 1867,
 'blighter': 3197,
 'got': 12536,
 'take': 30155,
 'chill': 5355,
 'blood': 3238,
 'lacklustr': 17007,
 'chow': 5457,
 'scene': 26647,
 'futil': 11617,
 'bid': 2932,
 'win': 34035,
 'gore': 12501,
 'hound': 14327,
 'final': 10741,
 'kill': 16531,
 'victim': 33095,
 'drench': 8787,
 'suitabl': 29641,
 'tasteless': 30310,
 'aka': 554,
 'uk': 31908,
 'instantli': 15189,
 'forgett': 11169,
 'trash': 31402,
 'clunker': 5807,
 'filmographi': 10728,
 'simpl': 27784,
 'premis': 23842,
 'succe': 29585,
 'mission': 19908,
 'entertain': 9668,
 'rang': 24724,
 'ridicul': 25582,
 'sublim': 29532,
 'physic': 23096,
 'exist': 10101,
 'alongsid': 762,
 'nice': 21033,
 'veteran': 33052,
 'turn': 31728,
 'bob': 3333,
 'newhart': 20994,
 'kevin': 16450,
 'kline': 16666,
 'predict': 23805,
 'excel': 10045,
 'form': 11179,
 'tom': 31102,
 'selleck': 27046,
 'play': 23342,
 'squar': 28873,
 'jaw': 15689,
 'lead': 17329,
 'man': 18617,
 'mr': 20397,
 'well': 33725,
 'display': 8320,
 'make': 18514,
 'success': 29587,
 'homosexu': 14170,
 'theme': 30657,
 'advanc': 346,
 'sort': 28516,
 'sinist': 27826,
 'hidden': 13858,
 'liber': 17598,
 'agenda': 437,
 'point': 23475,
 'fact': 10263,
 'viewer': 33137,
 'byproduct': 4347,
 'terrif': 30545,
 'profession': 24029,
 'frequent': 11408,
 'tongu': 31135,
 'cheek': 5227,
 'found': 11237,
 'laugh': 17240,
 'right': 25606,
 'moment': 20072,
 'solid': 28397,
 'usual': 32726,
 'teen': 30412,
 'high': 13876,
 'school': 26729,
 'genr': 11963,
 'realli': 24885,
 'lack': 17001,
 'origin': 21902,
 'four': 11244,
 'friend': 11439,
 'cheat': 5211,
 'way': 33636,
 'strain': 29321,
 'friendship': 11443,
 'depth': 7794,
 'stori': 29280,
 'attent': 1750,
 'full': 11540,
 'length': 17480,
 'bad': 2061,
 'actor': 231,
 'dialog': 7990,
 'tripe': 31532,
 'must': 20570,
 'wonder': 34208,
 'earth': 9103,
 'produc': 24020,
 'could': 6586,
 'come': 6010,
 'across': 221,
 'project': 24052,
 'theatric': 30638,
 'andrew': 1026,
 'gurland': 12997,
 'hack': 13062,
 'burn': 4240,
 'hitch': 13989,
 'romant': 25845,
 'actual': 235,
 'romanc': 25840,
 'mediocr': 19286,
 'horribl': 14271,
 'smith': 28173,
 'eva': 9947,
 'mend': 19401,
 'fun': 11554,
 'light': 17653,
 'feather': 10501,
 'journey': 15994,
 'aww': 1936,
 'sweet': 29935,
 'alex': 648,
 'hitchen': 13994,
 'proclaim': 24008,
 'doctor': 8456,
 'help': 13688,
 'hopeless': 14231,
 'guy': 13023,
 'albert': 606,
 'allegra': 706,
 'amber': 855,
 'valletta': 32811,
 'unfortun': 32287,
 'deal': 7430,
 'gossip': 12532,
 'columnist': 5997,
 'bent': 2744,
 'break': 3789,
 'pretti': 23907,
 'standard': 28971,
 'slapstick': 27983,
 'energet': 9593,
 'clearli': 5689,
 'sharp': 27341,
 'rapid': 24749,
 'fire': 10785,
 'chemistri': 5261,
 'real': 24879,
 'discoveri': 8234,
 'seen': 27001,
 'show': 27576,
 'king': 16575,
 'queen': 24468,
 'heartfelt': 13559,
 'prove': 24146,
 'fat': 10433,
 'white': 33875,
 'men': 19393,
 'cannot': 4557,
 'danc': 7246,
 'hip': 13947,
 'hop': 14227,
 'hilari': 13903,
 'hot': 14306,
 'bounci': 3620,
 'geez': 11905,
 'match': 18952,
 'tad': 30108,
 'long': 17948,
 'near': 20832,
 'redeem': 25021,
 'happi': 13289,
 'fill': 10704,
 'refresh': 25091,
 'cooki': 6407,
 'cutter': 7103,
 'litter': 17804,
 'theater': 30633,
 'vivaci': 33276,
 'irrepress': 15430,
 'ann': 1109,
 'gabl': 11640,
 'bring': 3915,
 'unlook': 32389,
 'live': 17817,
 'lone': 17941,
 'old': 21691,
 'sister': 27859,
 'brother': 3995,
 'princ': 23956,
 'edward': 9231,
 'island': 15470,
 'luci': 18140,
 'maud': 19024,
 'montgomeri': 20164,
 'novel': 21350,
 'liter': 17792,
 'exactli': 10030,
 'touch': 31244,
 'deserv': 7839,
 'portray': 23657,
 'actress': 234,
 'shirley': 27493,
 'joy': 16004,
 'red': 25014,
 'head': 13510,
 'fourteen': 11246,
 'year': 34534,
 'orphan': 21923,
 'complet': 6093,
 'alter': 783,
 'new': 20981,
 'guardian': 12880,
 'assur': 1655,
 'star': 28993,
 'role': 25824,
 'miss': 19902,
 'delight': 7634,
 'boundless': 3625,
 'quick': 24492,
 'temper': 30462,
 'secret': 26964,
 'sorrow': 28515,
 'stern': 29153,
 'spinster': 28742,
 'girl': 12190,
 'helen': 13656,
 'westley': 33770,
 'command': 6028,
 'woman': 34202,
 'slowli': 28107,
 'unbend': 32017,
 'affect': 379,
 'child': 5342,
 'innoc': 15132,
 'australian': 1823,
 'heggi': 13625,
 'finest': 10754,
 'shi': 27445,
 'welcom': 33719,
 'heart': 13550,
 'arriv': 1516,
 'fetch': 10634,
 'railroad': 24626,
 'station': 29051,
 'brown': 4004,
 'agreeabl': 468,
 'schoolboy': 26731,
 'quickli': 24498,
 'grab': 12569,
 'sara': 26443,
 'haden': 13077,
 'appropri': 1329,
 'prickli': 23932,
 'nosi': 21308,
 'neighbor': 20893,
 'charley': 5149,
 'grapewin': 12644,
 'avonlea': 1900,
 'twice': 31797,
 'invigor': 15359,
 'comput': 6124,
 'inspir': 15180,
 'technolog': 30399,
 'fresh': 11411,
 'stoke': 29243,
 'furnac': 11595,
 'poetic': 23466,
 'passion': 22550,
 'heat': 13572,
 'infatu': 15047,
 'allur': 733,
 'hold': 14086,
 'tell': 30453,
 'mind': 19752,
 'need': 20864,
 'realiti': 24883,
 'ever': 9970,
 'hire': 13962,
 'post': 23676,
 'offic': 21615,
 'far': 10374,
 'beyond': 2882,
 'test': 30569,
 'postal': 23677,
 'difficult': 8062,
 'stupid': 29485,
 'everyon': 9989,
 'go': 12343,
 'entir': 9677,
 'elev': 9376,
 'puzzl': 24381,
 'serious': 27153,
 'start': 29031,
 'without': 34141,
 'key': 16455,
 'sad': 26224,
 'mess': 19505,
 'mom': 20071,
 'dress': 8790,
 'though': 30789,
 'sender': 27077,
 'soon': 28472,
 'possibl': 23675,
 'word': 34258,
 'vh': 33063,
 'rental': 25276,
 'satellit': 26489,
 'fool': 11099,
 'moder': 20008,
 'known': 16725,
 'kistofferson': 16626,
 'henriksen': 13727,
 'soundtrack': 28550,
 'music': 20553,
 'monument': 20171,
 'valley': 32812,
 'sceneri': 26648,
 'curli': 7052,
 'hair': 13111,
 'fight': 10691,
 'mayb': 19061,
 'aw': 1907,
 'hard': 13304,
 'describ': 7828,
 'narrow': 20727,
 'human': 14433,
 'better': 2855,
 'bore': 3556,
 'untal': 32561,
 'compel': 6080,
 'cheesi': 5243,
 'camera': 4479,
 'recept': 24952,
 'nation': 20765,
 'forest': 11155,
 'asham': 1585,
 'paid': 22296,
 'lousi': 18064,
 'pictur': 23131,
 'hope': 14229,
 'nobodi': 21188,
 'sequel': 27124,
 'similar': 27771,
 'wors': 34300,
 'storylin': 29292,
 'british': 3939,
 'seem': 26997,
 'raven': 24817,
 'appetit': 1303,
 'feebl': 10520,
 'effort': 9255,
 'unintent': 32349,
 'parodi': 22497,
 'classic': 5645,
 'elabor': 9332,
 'misunderstand': 19933,
 'depart': 7770,
 'train': 31336,
 'declar': 7506,
 'dimension': 8113,
 'caricatur': 4674,
 'save': 26537,
 'hewitt': 13822,
 'cohes': 5901,
 'threaten': 30803,
 'spiral': 28743,
 'control': 6379,
 'plausibl': 23341,
 'progress': 24049,
 'natur': 20771,
 'suspens': 29851,
 'belief': 2655,
 'crash': 6738,
 'preposter': 23857,
 'bridget': 3877,
 'not': 21315,
 'hill': 13907,
 'kind': 16561,
 'experi': 10127,
 'gandhi': 11746,
 'mostli': 20305,
 'freedom': 11370,
 'fighter': 10692,
 'heard': 13543,
 'highlight': 13886,
 'stress': 29376,
 'hit': 13987,
 'territori': 30551,
 'explor': 10147,
 'dark': 7302,
 'shown': 27587,
 'courag': 6630,
 'dwell': 9046,
 'fortunetli': 11220,
 'anil': 1083,
 'kapoor': 16221,
 'feroz': 10614,
 'abbad': 37,
 'khan': 16470,
 'south': 28562,
 'africa': 410,
 'wife': 33962,
 'latter': 17230,
 'akshay': 570,
 'haril': 13327,
 'join': 15926,
 'becom': 2540,
 'barrist': 2329,
 'dream': 8757,
 'took': 31147,
 'overturn': 22199,
 'push': 24354,
 'motiv': 20321,
 'showcas': 27579,
 'practic': 23747,
 'formal': 11182,
 'educ': 9226,
 'walk': 33469,
 'footstep': 11117,
 'fail': 10282,
 'toward': 31274,
 'big': 2945,
 'path': 22583,
 'repuls': 25344,
 'defeat': 7549,
 'term': 30528,
 'pursu': 24348,
 'left': 17404,
 'india': 14972,
 'unsuccess': 32546,
 'bigger': 2951,
 'leav': 17364,
 'reader': 24869,
 'catch': 4844,
 'tenur': 30516,
 'absolut': 109,
 'convinc': 6392,
 'reach': 24859,
 'room': 25882,
 'dead': 7411,
 'bodi': 3355,
 'place': 23284,
 'fine': 10749,
 'develop': 7910,
 'darshan': 7333,
 'jariwala': 15666,
 'mk': 19962,
 'abl': 66,
 'larger': 17163,
 'quit': 24524,
 'eas': 9113,
 'shefali': 27392,
 'chaya': 5197,
 'shah': 27270,
 'kasturba': 16281,
 'brilliant': 3904,
 'alreadi': 774,
 'metal': 19526,
 'serial': 27151,
 'bhumika': 2907,
 'chawla': 5196,
 'candidatur': 4535,
 'wast': 33583,
 'justifi': 16109,
 'techniqu': 30395,
 'cinematographi': 5563,
 'especi': 9850,
 'duo': 8983,
 'tone': 31132,
 'color': 5979,
 'picturis': 23134,
 'costum': 6567,
 'context': 6348,
 'overal': 22091,
 'defiantli': 7564,
 'slow': 28102,
 'impati': 14783,
 'may': 19056,
 'insight': 15165,
 'area': 1409,
 'brought': 3999,
 'silver': 27757,
 'screen': 26849,
 'till': 30921,
 'connect': 6249,
 'worn': 34294,
 'critic': 6855,
 'averag': 1884,
 'watcher': 33597,
 'occupi': 21549,
 'seat': 26942,
 'strangest': 29330,
 'intens': 15226,
 'muckerji': 20420,
 'melandez': 19343,
 'spoke': 28794,
 'wit': 34120,
 'window': 34053,
 'descript': 7829,
 'roll': 25828,
 'refer': 25073,
 'greek': 12699,
 'accent': 145,
 'boyer': 3672,
 'taken': 30161,
 'poison': 23488,
 'last': 17201,
 'smack': 28131,
 'etc': 9898,
 'buy': 4323,
 'dan': 7244,
 'seymour': 27233,
 'plump': 23423,
 'foreign': 11146,
 'sultan': 29656,
 'polic': 23512,
 'chief': 5328,
 'appear': 1292,
 'casablanca': 4776,
 'georg': 11991,
 'jungl': 16087,
 'brendon': 3835,
 'fraiser': 11276,
 'forgot': 11173,
 'ten': 30480,
 'sit': 27864,
 'channel': 5089,
 'bought': 3614,
 'grown': 12836,
 'bredon': 3817,
 'what': 33799,
 'french': 11398,
 'millionair': 19726,
 'owner': 22217,
 'tobacco': 31047,
 'factori': 10268,
 'african': 411,
 'nearli': 20836,
 'madagascar': 18366,
 'loui': 18051,
 'jean': 15718,
 'paul': 22630,
 'belmondo': 2677,
 'singl': 27818,
 'advertis': 356,
 'bride': 3871,
 'gorgeou': 12505,
 'julia': 16061,
 'catherin': 4862,
 'deneuv': 7722,
 'spontan': 28802,
 'attract': 1760,
 'marri': 18844,
 'suddenli': 29609,
 'disappear': 8187,
 'eye': 10211,
 'privat': 23976,
 'bouquet': 3628,
 'trail': 31332,
 'previou': 23918,
 'later': 17214,
 'encount': 9565,
 'hall': 13153,
 'spite': 28750,
 'delus': 7663,
 'goe': 12388,
 'enamor': 9552,
 'enigmat': 9622,
 'splendid': 28764,
 'drama': 8735,
 'plenti': 23378,
 'betray': 2847,
 'decept': 7496,
 'theft': 30646,
 'hitchcockian': 13992,
 'young': 34627,
 'proprietari': 24106,
 'cigarett': 5533,
 'determin': 7886,
 'fall': 10312,
 'spell': 28684,
 'femm': 10575,
 'fatal': 10435,
 'suspect': 29848,
 'heroin': 13781,
 'sever': 27200,
 'cinema': 5549,
 'truffaut': 31626,
 'blow': 3273,
 'fervent': 10626,
 'moviego': 20367,
 'johnni': 15920,
 'guitar': 12932,
 'colorado': 5980,
 'jim': 15840,
 'bogart': 3378,
 'hitchcock': 13990,
 'usa': 32705,
 'version': 33033,
 'cut': 7089,
 'numer': 21409,
 'minut': 19812,
 'urgent': 32686,
 'restor': 25403,
 'remast': 25219,
 'loos': 17993,
 'base': 2356,
 'waltz': 33504,
 'cornel': 6489,
 'woolrich': 34246,
 'rear': 24900,
 ...}

In [37]:
y = df.iloc[:,-1].values

In [38]:
y.shape

(10000,)

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [41]:
print(X_train.shape) , print(X_test.shape)

(8000, 34902)
(2000, 34902)

(None, None)

In [42]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB
gnb = GaussianNB()
mnb = MultinomialNB()
bnb=BernoulliNB()

In [43]:
gnb.fit(X_train, y_train)
mnb.fit(X_train, y_train)
bnb.fit(X_train, y_train)

BernoulliNB()

In [44]:
y_pred_gnb = gnb.predict(X_test)
y_pred_mnb = mnb.predict(X_test)
y_pred_bnb = bnb.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
print('Gausian NB Accuracy: ', accuracy_score(y_test , y_pred_gnb))
print('Multinomial NB Accuracy: ', accuracy_score(y_test , y_pred_mnb))
print('Bernaulli NB Accuracy: ', accuracy_score(y_test , y_pred_bnb))

Gausian NB Accuracy:  0.6345
Multinomial NB Accuracy:  0.853
Bernaulli NB Accuracy:  0.8655

# Predictions

In [179]:
test_review= pd.Series({'test_review_1':  'The movie is very good i really enjoyed it , this is super mindblowing extraordinary', 'test_review_2': 'movie is really bad' , 'test_review_3': 'i did not like the movie' , 'test_review_4':'overall a good movie, and should give credit to the maker, director , actor all have acted well,story is super and direction is excellent, script is very good'})

In [180]:
test_review = pd.DataFrame(test_review )

In [181]:
test_review.reset_index(drop= True , inplace=True)

In [182]:
test_review.rename(columns= {0: 'review'} , inplace=True)

In [183]:
test_review

                                              review
0  The movie is very good i really enjoyed it , t...
1                                movie is really bad
2                           i did not like the movie
3  overall a good movie, and should give credit t...

In [184]:
X = test_review.copy()

In [185]:
corpus = []

for i in range(len(test_review['review'])):
    
    text = re.sub('[^a-zA-Z]' , ' ' , test_review['review'][i])
    text = text.lower()
    text = text.split()
    
    text = [ps.stem(word) for word in text if word not in set(stopwords.words('english'))]
    
    text = ' '.join(text)
    corpus.append(text)

In [186]:
X['review'] = corpus

In [187]:
X

                                              review
0  movi good realli enjoy super mindblow extraord...
1                                    movi realli bad
2                                          like movi
3  overal good movi give credit maker director ac...

In [188]:
X = cv.transform(X['review']).toarray()

In [189]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [190]:
pred = mnb.predict(X)

In [191]:
pred

array([1, 0, 0, 0], dtype=int64)

In [192]:
test_review['predictions'] = pred

In [193]:
test_review

                                              review  predictions
0  The movie is very good i really enjoyed it , t...            1
1                                movie is really bad            0
2                           i did not like the movie            0
3  overall a good movie, and should give credit t...            0